{
    "source": "BDSA",
    "name": "BDSA-2020-3417",
    "title": "Jupyter Notebook Vulnerable to Open Redirect via Improper Validation in 'handlers.py'",
    "description": "Jupyter Notebook does not validate URLs before users are redirected. An attacker could exploit this flaw to redirect users to arbitrary websites.",
    "technicalDescription": "This vulnerability mainly exists in `notebook/base/handlers.py`. This file does not properly validate URLs before redirection takes place. This could allow an attacker to redirect a victim to malicious websites.",
    "publishedDate": "2020-11-19T13:53:44.618Z",
    "updatedDate": "2020-11-19T13:53:44.610Z",
    "disclosureDate": "2020-11-18T00:00:00.000Z",
    "solution": "Fixed in [**6.1.5**](https://github.com/jupyter/notebook/releases/tag/6.1.5) by [this](https://github.com/jupyter/notebook/commit/3cec4bbe21756de9f0c4bccf18cf61d840314d74) commit.",
    "severity": "LOW",
    "cvss2": {
        "baseScore": 2.1,
        "impactSubscore": 2.9,
        "exploitabilitySubscore": 3.9,
        "severity": "LOW",
        "accessVector": "NETWORK",
        "accessComplexity": "HIGH",
        "authentication": "SINGLE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "PARTIAL",
        "availabilityImpact": "NONE",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 1.6
        },
        "vector": "(AV:N/AC:H/Au:S/C:N/I:P/A:N/E:U/RL:OF/RC:C)"
    },
    "cvss3": {
        "baseScore": 3.0,
        "impactSubscore": 1.4,
        "exploitabilitySubscore": 1.3,
        "severity": "LOW",
        "attackVector": "NETWORK",
        "attackComplexity": "HIGH",
        "confidentialityImpact": "NONE",
        "integrityImpact": "LOW",
        "availabilityImpact": "NONE",
        "privilegesRequired": "LOW",
        "scope": "CHANGED",
        "userInteraction": "REQUIRED",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 2.6
        },
        "vector": "CVSS:3.1/AV:N/AC:H/PR:L/UI:R/S:C/C:N/I:L/A:N/E:U/RL:O/RC:C"
    },
    "useCvss3": true,
    "classifications": [],
    "zeroDay": false,
    "underReview": false,
    "parentAdvisory": false,
    "credit": "zhuonan li",
    "workaround": "",
    "vendorFixDate": "2020-11-06T00:00:00.000Z",
    "bdsaTags": [],
    "overallScore": 2.6,
    "_meta": {
        "allow": [
            "GET"
        ],
        "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2020-3417",
        "links": [
            {
                "rel": "cwes",
                "href": "https://trendmicro2.app.blackduck.com/api/cwes/CWE-601"
            },
            {
                "rel": "related-vulnerability",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/CVE-2020-26215",
                "label": "NVD"
            },
            {
                "rel": "bdsa-ranges",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2020-3417/ranges"
            },
            {
                "rel": "reference",
                "href": "https://github.com/jupyter/notebook/commit/3cec4bbe21756de9f0c4bccf18cf61d840314d74",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/jupyter/notebook/releases/tag/6.1.5",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://github.com/jupyter/notebook/security/advisories/GHSA-c7vm-f5p4-8fqh",
                "label": "ADVISORY"
            },
            {
                "rel": "default-remediation-status",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2020-3417/default-remediation-status"
            }
        ]
    }
}