{
    "source": "BDSA",
    "name": "BDSA-2019-4493",
    "title": "Python Vulnerable to Denial-of-Service (DoS) via Infinite Loop in 'tarfile' Module",
    "description": "Python is vulnerable to denial-of-service (DoS) due to an infinite loop. An attacker could provide a specially crafted TAR file to the `tarfile` module that could cause DoS.",
    "technicalDescription": "The DoS is possible due to the function `_proc_pax()` in file `Lib/tarfile.py` entering an infinite loop if the supplied file's `PAX` header's length is 0.",
    "publishedDate": "2020-07-14T13:19:16.055Z",
    "updatedDate": "2020-08-24T15:55:35.847Z",
    "disclosureDate": "2019-12-10T00:00:00.000Z",
    "exploitPublishDate": "2019-12-10T00:00:00.000Z",
    "solution": "Fixed in:\n* **[3.9.0-b5](https://github.com/python/cpython/releases/tag/v3.9.0b5)** by [this](https://github.com/python/cpython/commit/f3232294ee) commit\n* **[3.8.5](https://github.com/python/cpython/releases/tag/v3.8.5)** by [this](https://github.com/python/cpython/commit/c55479556d) commit\n* **[3.7.9](https://github.com/python/cpython/releases/tag/v3.7.9)** by [this](https://github.com/python/cpython/commit/79c6b602ef) commit\n* **[3.6.12](https://github.com/python/cpython/releases/tag/v3.6.12)** by [this](https://github.com/python/cpython/commit/47a2955589) commit\n*  **[3.5.10-rc1](https://github.com/python/cpython/releases/tag/v3.5.10rc1)** by [this](https://github.com/python/cpython/commit/cac9ca8ed9) commit\n\n.",
    "severity": "MEDIUM",
    "cvss2": {
        "baseScore": 5.0,
        "impactSubscore": 2.9,
        "exploitabilitySubscore": 10.0,
        "severity": "LOW",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "PARTIAL",
        "temporalMetrics": {
            "exploitability": "PROOF_OF_CONCEPT",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 3.9
        },
        "vector": "(AV:N/AC:L/Au:N/C:N/I:N/A:P/E:POC/RL:OF/RC:C)"
    },
    "cvss3": {
        "baseScore": 5.3,
        "impactSubscore": 1.4,
        "exploitabilitySubscore": 3.9,
        "severity": "MEDIUM",
        "attackVector": "NETWORK",
        "attackComplexity": "LOW",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "LOW",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "temporalMetrics": {
            "exploitability": "PROOF_OF_CONCEPT",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 4.8
        },
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L/E:P/RL:O/RC:C"
    },
    "useCvss3": true,
    "classifications": [],
    "zeroDay": false,
    "underReview": false,
    "parentAdvisory": false,
    "credit": "jvoisin",
    "workaround": "",
    "vendorFixDate": "2020-07-15T00:00:00.000Z",
    "vendorNotifiedDate": "2019-12-10T00:00:00.000Z",
    "bdsaTags": [],
    "overallScore": 4.8,
    "_meta": {
        "allow": [
            "GET"
        ],
        "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2019-4493",
        "links": [
            {
                "rel": "cwes",
                "href": "https://trendmicro2.app.blackduck.com/api/cwes/CWE-835"
            },
            {
                "rel": "related-vulnerability",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/CVE-2019-20907",
                "label": "NVD"
            },
            {
                "rel": "bdsa-ranges",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2019-4493/ranges"
            },
            {
                "rel": "reference",
                "href": "https://bugs.python.org/issue39017",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://bugs.python.org/issue39017",
                "label": "POC"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/commit/47a2955589",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/commit/79c6b602ef",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/commit/c55479556d",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/commit/cac9ca8ed9",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/commit/f3232294ee",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/releases/tag/v3.5.10rc1",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/releases/tag/v3.6.12",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/releases/tag/v3.7.9",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/releases/tag/v3.8.5",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/releases/tag/v3.9.0b5",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "default-remediation-status",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2019-4493/default-remediation-status"
            }
        ]
    }
}