{
    "source": "BDSA",
    "name": "BDSA-2019-3129",
    "title": "Rsyslog Vulnerable to Denial-of-Service (DoS) via Out-of-Bounds Access in 'pmdb2diag.c' File",
    "description": "Rsyslog contains an out-of-bounds access vulnerability. An attacker could exploit this by supplying a crafted log message to the system causing a denial-of-service (DoS) condition via an application crash.",
    "technicalDescription": "The vulnerability occurs due to insufficient sanity checks after the bounds check on the `level` length in the `contrib/pmdb2diag/pmdb2diag.c` file.",
    "publishedDate": "2019-10-03T13:02:18.291Z",
    "updatedDate": "2019-10-03T13:02:18.276Z",
    "disclosureDate": "2019-09-24T00:00:00.000Z",
    "solution": "Fixed in version [**8.1910.0**](https://github.com/rsyslog/rsyslog/releases/tag/v8.1910.0) by [this](https://github.com/rsyslog/rsyslog/commit/b0894088b680666035a3418326e13bc99d4fed49) commit.",
    "severity": "MEDIUM",
    "cvss2": {
        "baseScore": 5.0,
        "impactSubscore": 2.9,
        "exploitabilitySubscore": 10.0,
        "severity": "LOW",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "PARTIAL",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 3.7
        },
        "vector": "(AV:N/AC:L/Au:N/C:N/I:N/A:P/E:U/RL:OF/RC:C)"
    },
    "cvss3": {
        "baseScore": 5.3,
        "impactSubscore": 1.4,
        "exploitabilitySubscore": 3.9,
        "severity": "MEDIUM",
        "attackVector": "NETWORK",
        "attackComplexity": "LOW",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "LOW",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 4.6
        },
        "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L/E:U/RL:O/RC:C"
    },
    "useCvss3": true,
    "classifications": [],
    "zeroDay": false,
    "underReview": false,
    "parentAdvisory": false,
    "workaround": "",
    "vendorFixDate": "2019-09-30T00:00:00.000Z",
    "bdsaTags": [],
    "overallScore": 4.6,
    "_meta": {
        "allow": [
            "GET"
        ],
        "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2019-3129",
        "links": [
            {
                "rel": "cwes",
                "href": "https://trendmicro2.app.blackduck.com/api/cwes/CWE-787"
            },
            {
                "rel": "related-vulnerability",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/CVE-2019-17040",
                "label": "NVD"
            },
            {
                "rel": "bdsa-ranges",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2019-3129/ranges"
            },
            {
                "rel": "reference",
                "href": "https://github.com/rsyslog/rsyslog/commit/b0894088b680666035a3418326e13bc99d4fed49",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/rsyslog/rsyslog/pull/3875",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://github.com/rsyslog/rsyslog/releases/tag/v8.1910.0",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "default-remediation-status",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2019-3129/default-remediation-status"
            }
        ]
    }
}