{
    "source": "BDSA",
    "name": "BDSA-2020-1616",
    "title": "Python Vulnerable to Local Code Inclusion via Improper 'python3.dll' Load Path Setup",
    "description": "Python for Windows loads its core module from untrusted locations when trying to pre-load the `python3.dll` file. This means it could load another `python3.dll` file placed by an attacker which would execute arbitrary malicious instructions.\n\nThis issue is only triggered in applications that have Python embedded, but not running `python.exe` on its own.",
    "technicalDescription": "The issue is due to an incorrect path setup during initialization when function `Py_SetPath()` is called. This function causes another function, `getpathp.c::calculate_path()`, not to be called later on. Since `getpathp.c::calculate_path()` is the only method that sets the `dllpath` variable that stores the base search path, it remains empty by default. The empty `dllpath` is later joined with `\\python3.dll` and `\\DLLs\\python3.dll` in order to construct the full search path. Since the base path is empty, `python3.dll` is unintentionally searched and loaded from the root location of the windows drive the application is running from.",
    "publishedDate": "2020-07-08T15:14:33.927Z",
    "updatedDate": "2020-09-08T15:17:19.533Z",
    "disclosureDate": "2020-07-06T00:00:00.000Z",
    "solution": "Fixed in:\n* [**3.9.0-b5**](https://github.com/python/cpython/releases/tag/v3.9.0b5) by [this](https://github.com/python/cpython/commit/4981fe36c7477303de830e8dca929a02caaaffe4) commit.\n* [**3.8.4**](https://github.com/python/cpython/releases/tag/v3.8.5) by [this](https://github.com/python/cpython/commit/aa7f7756149a10c64d01f583b71e91814db886ab) commit.\n* [**3.7.9**](https://github.com/python/cpython/releases/tag/v3.7.9) by [this](https://github.com/python/cpython/commit/4bfcffe16e9742c154f54ae96b5b36903500abaa) commit.\n* [**3.6.12**](https://github.com/python/cpython/releases/tag/v3.6.12) by [this](https://github.com/python/cpython/commit/46cbf6148a46883110883488d3e9febbe46ba861) commit.\n\nThe latest stable releases are available [here](https://www.python.org/downloads/).",
    "severity": "HIGH",
    "cvss2": {
        "baseScore": 4.6,
        "impactSubscore": 6.4,
        "exploitabilitySubscore": 3.9,
        "severity": "LOW",
        "accessVector": "LOCAL",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "PARTIAL",
        "availabilityImpact": "PARTIAL",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 3.4
        },
        "vector": "(AV:L/AC:L/Au:N/C:P/I:P/A:P/E:U/RL:OF/RC:C)"
    },
    "cvss3": {
        "baseScore": 8.4,
        "impactSubscore": 5.9,
        "exploitabilitySubscore": 2.5,
        "severity": "HIGH",
        "attackVector": "LOCAL",
        "attackComplexity": "LOW",
        "confidentialityImpact": "HIGH",
        "integrityImpact": "HIGH",
        "availabilityImpact": "HIGH",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "temporalMetrics": {
            "exploitability": "UNPROVEN",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 7.3
        },
        "vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H/E:U/RL:O/RC:C"
    },
    "useCvss3": true,
    "classifications": [],
    "zeroDay": false,
    "underReview": false,
    "parentAdvisory": false,
    "credit": "Eric Gantumur",
    "workaround": "The official mitigation to this issue would be to explicitly call `LoadLibrary()` on a trusted copy of \n`python3.dll` before calling `Py_Initialize()`.",
    "vendorFixDate": "2020-07-06T00:00:00.000Z",
    "vendorNotifiedDate": "2017-03-10T00:00:00.000Z",
    "bdsaTags": [],
    "overallScore": 7.3,
    "_meta": {
        "allow": [
            "GET"
        ],
        "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2020-1616",
        "links": [
            {
                "rel": "cwes",
                "href": "https://trendmicro2.app.blackduck.com/api/cwes/CWE-426"
            },
            {
                "rel": "related-vulnerability",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/CVE-2020-15523",
                "label": "NVD"
            },
            {
                "rel": "bdsa-ranges",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2020-1616/ranges"
            },
            {
                "rel": "reference",
                "href": "https://bugs.python.org/issue29778",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://bugs.python.org/issue29778",
                "label": "WORKAROUND"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/commit/46cbf6148a46883110883488d3e9febbe46ba861",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/commit/4981fe36c7477303de830e8dca929a02caaaffe4",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/commit/4bfcffe16e9742c154f54ae96b5b36903500abaa",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/commit/aa7f7756149a10c64d01f583b71e91814db886ab",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/commit/dcbaa1b49cd9062fb9ba2b9d49555ac6cd8c60b5",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/pull/21297",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/releases/tag/v3.6.12",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/releases/tag/v3.7.9",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/releases/tag/v3.8.5",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://github.com/python/cpython/releases/tag/v3.9.0b5",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://mail.python.org/archives/list/security-announce@python.org/thread/C5RIXC2ZIML3NOEIOGFPA6ISGU5L2QXL/",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://www.python.org/downloads/",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "default-remediation-status",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2020-1616/default-remediation-status"
            }
        ]
    }
}