{
    "source": "BDSA",
    "name": "BDSA-2019-4252",
    "title": "PyYAML Vulnerable to Remote Code Execution (RCE) via Unsafe 'yaml.load' API with 'FullLoader' Loader",
    "description": "PyYAML is vulnerable to arbitrary code execution due to insufficient protections against unsafe execution with the `yaml.load` API. An attacker could exploit this vulnerability by supplying a system with maliciously crafted data.\n\nNote that this issue exists due to an incomplete fix for CVE-2017-18342 (BDSA-2017-3843).",
    "technicalDescription": "PyYAML attempts to disallow the execution of arbitrary functions when using the default loader `FullLoader` with the `yaml.load()` function. However, this protection is not sufficient and code execution is still possible by leveraging standard library modules, such as `subprocess.Popen` to execute commands or `io.FileIO` to read/write arbitrary files.",
    "publishedDate": "2020-02-21T15:06:34.124Z",
    "updatedDate": "2021-02-11T16:39:53.528Z",
    "disclosureDate": "2019-07-16T00:00:00.000Z",
    "exploitPublishDate": "2019-11-13T00:00:00.000Z",
    "solution": "Fixed in **[5.2b1](https://github.com/yaml/pyyaml/releases/tag/5.2b1)** by these commits:\n* [Commit 1](https://github.com/yaml/pyyaml/commit/7b68405c81db889f83c32846462b238ccae5be80)\n* [Commit 2](https://github.com/yaml/pyyaml/commit/bbcf95fa051fdba9bbf879332e2f7999b195cf95)\n* [Commit 3](https://github.com/yaml/pyyaml/commit/8c5e47fe62d7b9e0282a176a4b79b8b2980dc704)\n\nThe latest stable releases are available [here](https://github.com/yaml/pyyaml/releases/).",
    "severity": "HIGH",
    "cvss2": {
        "baseScore": 7.5,
        "impactSubscore": 6.4,
        "exploitabilitySubscore": 10.0,
        "severity": "MEDIUM",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "PARTIAL",
        "availabilityImpact": "PARTIAL",
        "temporalMetrics": {
            "exploitability": "PROOF_OF_CONCEPT",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 5.9
        },
        "vector": "(AV:N/AC:L/Au:N/C:P/I:P/A:P/E:POC/RL:OF/RC:C)"
    },
    "cvss3": {
        "baseScore": 9.8,
        "impactSubscore": 5.9,
        "exploitabilitySubscore": 3.9,
        "severity": "HIGH",
        "attackVector": "NETWORK",
        "attackComplexity": "LOW",
        "confidentialityImpact": "HIGH",
        "integrityImpact": "HIGH",
        "availabilityImpact": "HIGH",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "temporalMetrics": {
            "exploitability": "PROOF_OF_CONCEPT",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 8.8
        },
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H/E:P/RL:O/RC:C"
    },
    "useCvss3": true,
    "classifications": [],
    "zeroDay": false,
    "underReview": false,
    "parentAdvisory": false,
    "credit": "James Pickering",
    "workaround": "",
    "vendorFixDate": "2019-11-18T00:00:00.000Z",
    "bdsaTags": [
        "RCE"
    ],
    "overallScore": 8.8,
    "_meta": {
        "allow": [
            "GET"
        ],
        "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2019-4252",
        "links": [
            {
                "rel": "cwes",
                "href": "https://trendmicro2.app.blackduck.com/api/cwes/CWE-95"
            },
            {
                "rel": "related-vulnerability",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/CVE-2019-20477",
                "label": "NVD"
            },
            {
                "rel": "bdsa-ranges",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2019-4252/ranges"
            },
            {
                "rel": "reference",
                "href": "https://github.com/yaml/pyyaml/commit/7b68405c81db889f83c32846462b238ccae5be80",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/yaml/pyyaml/commit/8c5e47fe62d7b9e0282a176a4b79b8b2980dc704",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/yaml/pyyaml/commit/bbcf95fa051fdba9bbf879332e2f7999b195cf95",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/yaml/pyyaml/issues/321",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://github.com/yaml/pyyaml/issues/5",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://github.com/yaml/pyyaml/releases/",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://github.com/yaml/pyyaml/releases/tag/5.2b1",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://www.exploit-db.com/docs/english/47655-yaml-deserialization-attack-in-python.pdf",
                "label": "POC"
            },
            {
                "rel": "default-remediation-status",
                "href": "https://trendmicro2.app.blackduck.com/api/vulnerabilities/BDSA-2019-4252/default-remediation-status"
            }
        ]
    }
}