{
    "source": "BDSA",
    "name": "BDSA-2020-4568",
    "title": "cryptography Package for Python Vulnerable to Information Exposure and Denial-of-Service (DoS) via Integer Overflow in 'openssl/ciphers.py'",
    "description": "The cryptography package for Python is vulnerable to information exposure and denial-of-service (DoS) via an integer overflow in `openssl/ciphers.py` which could subsequently cause buffer overflows. An attacker could exploit this by using certain sequences of `update()` during symmetric encryption of payloads in excess of **2GB**.",
    "technicalDescription": "This issue occurs in the `_CipherContext()` class within the `src/cryptography/hazmat/backends/openssl/ciphers.py`file due to improper logic. It was mitigated by switching from using `31` to using `30` within the calculation of `_MAX_CHUNK_SIZE`.",
    "publishedDate": "2021-07-29T13:23:34.324Z",
    "updatedDate": "2021-07-30T10:04:01.281Z",
    "disclosureDate": "2020-12-09T00:00:00.000Z",
    "exploitPublishDate": "2020-12-09T00:00:00.000Z",
    "solution": "Fixed in [**3.4**](https://github.com/pyca/cryptography/releases/tag/3.4) by [this](https://github.com/pyca/cryptography/commit/06cbf77371881e80ea4b5e349136dcc53749fc0c) commit.\nFixed in [**3.3.2**](https://github.com/pyca/cryptography/releases/tag/3.3.2) by [this](https://github.com/pyca/cryptography/commit/82b6ce28389f0a317bc55ba2091a74b346db7cae) commit.\n\nThe latest stable releases are available [here](https://github.com/pyca/cryptography/releases).",
    "severity": "HIGH",
    "cvss2": {
        "baseScore": 6.4,
        "impactSubscore": 4.9,
        "exploitabilitySubscore": 10.0,
        "severity": "MEDIUM",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "NONE",
        "availabilityImpact": "PARTIAL",
        "temporalMetrics": {
            "exploitability": "PROOF_OF_CONCEPT",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 5.0
        },
        "vector": "(AV:N/AC:L/Au:N/C:P/I:N/A:P/E:POC/RL:OF/RC:C)"
    },
    "cvss3": {
        "baseScore": 9.1,
        "impactSubscore": 5.2,
        "exploitabilitySubscore": 3.9,
        "severity": "HIGH",
        "attackVector": "NETWORK",
        "attackComplexity": "LOW",
        "confidentialityImpact": "HIGH",
        "integrityImpact": "NONE",
        "availabilityImpact": "HIGH",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "temporalMetrics": {
            "exploitability": "PROOF_OF_CONCEPT",
            "remediationLevel": "OFFICIAL_FIX",
            "reportConfidence": "CONFIRMED",
            "score": 8.2
        },
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H/E:P/RL:O/RC:C"
    },
    "useCvss3": true,
    "classifications": [],
    "zeroDay": false,
    "underReview": false,
    "parentAdvisory": false,
    "credit": "Anders Wenhaug gablank",
    "workaround": "",
    "vendorFixDate": "2021-02-07T00:00:00.000Z",
    "vendorNotifiedDate": "2020-12-09T00:00:00.000Z",
    "bdsaTags": [],
    "overallScore": 8.2,
    "_meta": {
        "allow": [],
        "href": "https://trendmicro.app.blackduck.com/api/vulnerabilities/BDSA-2020-4568",
        "links": [
            {
                "rel": "cwes",
                "href": "https://trendmicro.app.blackduck.com/api/cwes/CWE-120"
            },
            {
                "rel": "cwes",
                "href": "https://trendmicro.app.blackduck.com/api/cwes/CWE-190"
            },
            {
                "rel": "related-vulnerability",
                "href": "https://trendmicro.app.blackduck.com/api/vulnerabilities/CVE-2020-36242",
                "label": "NVD"
            },
            {
                "rel": "bdsa-ranges",
                "href": "https://trendmicro.app.blackduck.com/api/vulnerabilities/BDSA-2020-4568/ranges"
            },
            {
                "rel": "reference",
                "href": "https://github.com/pyca/cryptography/commit/06cbf77371881e80ea4b5e349136dcc53749fc0c",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/pyca/cryptography/commit/82b6ce28389f0a317bc55ba2091a74b346db7cae",
                "label": "PATCH"
            },
            {
                "rel": "reference",
                "href": "https://github.com/pyca/cryptography/commit/f90ba1808ee9bd9a13c5673b776484644f29d7ba",
                "label": "INTRODUCTORY_COMMIT"
            },
            {
                "rel": "reference",
                "href": "https://github.com/pyca/cryptography/issues/5615",
                "label": "ADVISORY"
            },
            {
                "rel": "reference",
                "href": "https://github.com/pyca/cryptography/issues/5615",
                "label": "POC"
            },
            {
                "rel": "reference",
                "href": "https://github.com/pyca/cryptography/releases",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://github.com/pyca/cryptography/releases/tag/3.3.2",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://github.com/pyca/cryptography/releases/tag/3.4",
                "label": "VENDOR_UPGRADE"
            },
            {
                "rel": "reference",
                "href": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/L7RGQLK4J5ZQFRLKCHVVG6BKZTUQMG7E/",
                "label": "ADVISORY"
            }
        ]
    }
}